name: _ (call) lint backend

on:
  workflow_call:

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Deelite34/actions/setup-backend@v2
      - uses: Deelite34/actions/lint-backend@v2
